backend:
  name: git-gateway
  branch: master

media_folder: "dist/static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "employment"
    label: "Employment Opportunities"
    folder: "employment"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/job.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Post Body", name: "body", widget: "markdown" }
