backend:
  name: git-gateway
  branch: master

media_folder: "/src/static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "employment"
    label: "Employment Opportunities"
    folder: "src/employment"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "job.njk"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Post Body"
        name: "body"
        widget: "markdown"

  - name: "news"
    label: "News Entries"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "news.njk"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Posted Date"
        name: "postDate"
        widget: "datetime"

      - label: "Post Body"
        name: "body"
        widget: "markdown"

      - label: "Image"
        name: "image"
        widget: "image"
        media_folder: "/static/uploads/news"
        required: false
        choose_url: true
        media_library:
          config:
            multiple: false
