backend:
  name: git-gateway
  branch: master

media_folder: "/src/static/uploads"
public_folder: "/static/uploads"
site_url: https://www.swimmaccarolina.org
display_url: https://www.swimmaccarolina.org
logo_url: https://www.swimmaccarolina.org/static/swimmac-logo.svg

collections:
  - name: "pages"
    label: "Page Content"
    folder: "src/pages"
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "pages.njk"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Post Body"
        name: "body"
        widget: "markdown"

  - name: "employment"
    label: "Employment Opportunities"
    folder: "src/employment"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "job.njk"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Post Body"
        name: "body"
        widget: "markdown"

  - name: "news"
    label: "News Entries"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "news.njk"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Posted Date"
        name: "postDate"
        widget: "datetime"

      - label: "Post Body"
        name: "body"
        widget: "markdown"

      - label: "Image"
        name: "image"
        widget: "image"
        media_folder: "/static/uploads/news"
        required: false
        choose_url: true
        media_library:
          config:
            multiple: false

  - name: "staff"
    label: "Staff Members"
    folder: "src/staff"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "staff.njk"
      - label: "Name"
        name: "title"
        widget: "string"
      - label: "Job Title"
        name: "jobTitle"
        widget: "string"
      - label: "Email"
        name: "email"
        widget: "string"
      - label: "Department"
        name: "department"
        widget: "select"
        multiple: true
        options:
          - { label: "Administration", value: "administration" }
          - { label: "Competitive Team Leadership", value: "competitive-team-leadership" }
          - { label: "Competitive Team Coaches", value: "competitive-team-coaches" }
          - { label: "Swim School", value: "swim-school" }
          - { label: "Pre-Comp Mac Fit & Homeschool", value: "bridge-programs" }
          - { label: "Masters Coaches", value: "masters-coaches" }
          - { label: "Board of Directors", value: "board" }
      - label: "Image"
        name: "staffImage"
        widget: "image"
        media_folder: "../static/staff"
        public_folder: "/static/staff"
        required: false
        choose_url: true
        default: "https://www.swimmaccarolina.org/static/staff/coach-avatar.jpg"
        media_library:
          config:
            multiple: false
      - label: "Order"
        name: "order"
        widget: "number"
        default: 100
        value_type: "int"
      - label: "Bio"
        name: "bio"
        widget: "markdown"
        required: false
